import { z } from "zod";

export const PropertySchema = z.object({
  id: z.string().optional(),
  street: z.string().optional(),
  city: z.string().optional(),
  zip_code: z.string().optional(),
  online_link: z.string().url().optional(),
  year_built: z.number().optional(),
  asking_price: z.number().optional(),
  offer_price: z.number().optional(),
  info: z.string().optional(),
  down_payment_percentage: z.number().optional(),
  renovations: z.number().optional(),
  closing_cost: z.number().optional(),
  interest_rate: z.number().optional(),
  years: z.number().optional(),
  property_tax_rate: z.number().optional(),
  property_sqft: z.number().optional(),
  lot_sqft: z.number().optional(),
  section8: z.boolean().optional(),
  lease: z.boolean().optional(),
  disclosure_or_inspections: z.boolean().optional(),
  down_payment: z.number().optional(),
  loan_amount: z.number().optional(),
  total_cost: z.number().optional(),
  monthly_mortgage: z.number().optional(),
  monthly_property_taxes: z.number().optional(),
  monthly_insurance: z.number().optional(),
  monthly_utilities: z.number().optional(),
  monthly_fees: z.number().optional(),
  total_monthly_cost: z.number().optional(),
  actual_monthly_rental_income: z.number().optional(),
  actual_net: z.number().optional(),
  actual_annual_net: z.number().optional(),
  actual_roi: z.number().optional(),
  actual_dcsr: z.number().optional(),
  actual_income_over_debt: z.number().optional(),
  actual_cap_rate: z.number().optional(),
  projected_monthly_rental_income: z.number().optional(),
  project_net: z.number().optional(),
  projected_annual_net: z.number().optional(),
  projected_roi: z.number().optional(),
  projected_dcsr: z.number().optional(),
  projected_income_over_debt: z.number().optional(),
  projected_cap_rate: z.number().optional(),
  years_until_maxed_rents: z.number().optional(),
});
